name: TurboAgent
main: net.nando256.turboagent.TwBridgePlugin
version: ${version}
api-version: "1.21"
author: nando256
softdepend: []
commands:
  tw:
    description: Get TurboWarp magic link
    permission: turboagent.link
    usage: /tw
permissions:
  turboagent.link:
    default: true
