name: twbridge
main: net.nando256.twbridge.TwBridgePlugin
version: ${version}
api-version: "1.21"
author: nando256
softdepend: []
commands:
  tw:
    description: Get TurboWarp magic link
    permission: twbridge.link
    usage: /tw
permissions:
  twbridge.link:
    default: true
